version: "3"

services:
    server:
        build: 
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "4000:4000"
        env_file: ./server/.env
        networks: 
            - app-network
    client:
        build: 
            context: ./client
            dockerfile: Dockerfile
        ports: 
            - "3000:3000"
        env_file: ./client/.env
        volumes:
            - ./client/:/usr/app
            - /usr/app/node_modules
        networks: 
            - app-network
    mongo:
        container_name: mongo
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - "27018:27017"
        networks: 
            - app-network

networks:
    app-network:
        driver: bridge